- name: Stop the sandbox instances
  ec2:
    aws_access_key: '{{ aws_access_key_id }}'
    aws_secret_key: '{{ aws_secret_access_key }}'
    instance_ids: '{{ instance_ids }}'
    region: '{{ region }}'
    state: stopped
    wait: True
    assign_public_ip: yes
